FROM node:22-bookworm-slim
WORKDIR /app

RUN corepack enable pnpm


COPY package.json pnpm-lock.yaml* pnpm-workspace.yaml ./

ENV CI=true
RUN pnpm install

COPY . .

RUN pnpm prisma generate

EXPOSE 3333

CMD ["sh", "-c", "pnpm prisma generate && pnpm tsx watch src/server.ts"]